# Generated by Django 4.2.28 on 2026-03-03 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('network', models.CharField(blank=True, help_text='Example: 192.168.1.0/24', max_length=50, null=True)),
                ('auto_generate', models.BooleanField(default=False, help_text='Automatically generate IP addresses from this network')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='example.com', max_length=255, unique=True)),
                ('server_ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('resolved_ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='monitoring.server')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='screenshots/')),
                ('http_status_code', models.PositiveIntegerField()),
                ('content_length', models.PositiveIntegerField(blank=True, null=True)),
                ('ssim_score', models.FloatField(blank=True, null=True)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='monitoring.site')),
            ],
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unpack_ipv4=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='monitoring.ipclass')),
            ],
            options={
                'unique_together': {('ip_class', 'ip_address')},
            },
        ),
    ]
