# Generated by Django 4.2.28 on 2026-03-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPAddress',
        ),
        migrations.DeleteModel(
            name='IPClass',
        ),
    ]
