# Generated by Django 4.2.28 on 2026-03-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_ipclass_remove_ipaddress_name_ipaddress_label_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ipaddress',
            unique_together={('ip_class', 'ip_address')},
        ),
    ]
