# Generated by Django 6.0.2 on 2026-03-03 11:16

import apps.monitoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_delete_ipaddress_delete_ipclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesnapshot',
            name='http_status_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesnapshot',
            name='screenshot',
            field=models.ImageField(upload_to=apps.monitoring.models.screenshot_upload_path),
        ),
    ]
