# Generated by Django 4.2.28 on 2026-03-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_ipaddress_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipclass',
            name='auto_generate',
            field=models.BooleanField(default=False, help_text='Automatically generate IP addresses from this network'),
        ),
        migrations.AddField(
            model_name='ipclass',
            name='network',
            field=models.CharField(blank=True, help_text='Example: 192.168.1.0/24', max_length=50, null=True),
        ),
    ]
