# Generated by Django 6.0.2 on 2026-03-03 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_sitesnapshot_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenshotComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssim_score', models.FloatField(blank=True, help_text='Structural Similarity Index (1 = identical, 0 = completely different)', null=True)),
                ('percent_difference', models.FloatField(blank=True, help_text='Percentage of pixels that changed', null=True)),
                ('changed_pixels', models.IntegerField(blank=True, help_text='Number of pixels that changed', null=True)),
                ('total_pixels', models.IntegerField(blank=True, help_text='Total number of pixels in the image', null=True)),
                ('heatmap', models.ImageField(blank=True, help_text='Visual heatmap showing changes', null=True, upload_to='comparisons/heatmaps/')),
                ('diff_image', models.ImageField(blank=True, help_text='Difference image highlighting changes', null=True, upload_to='comparisons/diffs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_comparisons', to='monitoring.sitesnapshot')),
                ('previous_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_comparisons', to='monitoring.sitesnapshot')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='monitoring.site')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('previous_snapshot', 'current_snapshot')},
            },
        ),
    ]
