# Generated by Django 6.0.2 on 2026-03-03 13:27

import apps.monitoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_screenshotcomparison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesnapshot',
            name='screenshot',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.monitoring.models.screenshot_upload_path),
        ),
    ]
