# Generated by Django 6.0.2 on 2026-03-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alter_sitesnapshot_screenshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesnapshot',
            options={'ordering': ['-taken_at']},
        ),
        migrations.AddField(
            model_name='sitesnapshot',
            name='is_baseline',
            field=models.BooleanField(default=False, help_text='If True, this is the baseline snapshot for comparisons'),
        ),
        migrations.AddConstraint(
            model_name='sitesnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_baseline', True)), fields=('site', 'is_baseline'), name='unique_baseline_per_site'),
        ),
    ]
