# Generated by Django 6.0.2 on 2026-03-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_alter_sitesnapshot_options_sitesnapshot_is_baseline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Server IPv4 address', null=True, protocol='IPv4'),
        ),
    ]
