# Generated by Django 6.0.2 on 2026-03-04 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_server_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_score', models.FloatField(blank=True, null=True)),
                ('seo_score', models.FloatField(blank=True, null=True)),
                ('security_score', models.FloatField(blank=True, null=True)),
                ('availability_score', models.FloatField(blank=True, null=True)),
                ('content_quality_score', models.FloatField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('page_load_time_ms', models.IntegerField(blank=True, null=True)),
                ('ttfb_ms', models.IntegerField(blank=True, null=True)),
                ('content_size_kb', models.IntegerField(blank=True, null=True)),
                ('has_ssl', models.BooleanField(default=False)),
                ('has_security_headers', models.BooleanField(default=False)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='monitoring.site')),
                ('snapshot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='monitoring.sitesnapshot')),
            ],
            options={
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['site', '-calculated_at'], name='monitoring__site_id_5d22f0_idx')],
            },
        ),
    ]
