# Generated by Django 6.0.2 on 2026-03-04 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_sitescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='continuous_monitoring',
            field=models.BooleanField(default=False, help_text='Enable automatic periodic monitoring'),
        ),
        migrations.AddField(
            model_name='site',
            name='monitoring_frequency',
            field=models.PositiveIntegerField(default=3, help_text='Monitoring frequency in minutes (1-1440)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)]),
        ),
    ]
