# Generated by Django 6.0.2 on 2026-03-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_site_continuous_monitoring_site_monitoring_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='last_monitored',
            field=models.DateTimeField(blank=True, help_text='Last time this site was automatically monitored', null=True),
        ),
    ]
