# Generated by Django 6.0.3 on 2026-03-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_site_last_monitored'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesnapshot',
            name='ticket',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
