# Generated by Django 6.0.3 on 2026-03-25 09:56

import apps.monitoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_sitesnapshot_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshotcomparison',
            name='diff_image',
            field=models.ImageField(blank=True, help_text='Difference image highlighting changes', null=True, storage='apps.monitoring.storage.RemoteUploaderStorage', upload_to='comparisons/diffs/'),
        ),
        migrations.AlterField(
            model_name='screenshotcomparison',
            name='heatmap',
            field=models.ImageField(blank=True, help_text='Visual heatmap showing changes', null=True, storage='apps.monitoring.storage.RemoteUploaderStorage', upload_to='comparisons/heatmaps/'),
        ),
        migrations.AlterField(
            model_name='sitesnapshot',
            name='screenshot',
            field=models.ImageField(blank=True, max_length=500, null=True, storage='apps.monitoring.storage.RemoteUploaderStorage', upload_to=apps.monitoring.models.screenshot_upload_path),
        ),
    ]
