# Generated by Django 6.0.3 on 2026-04-07 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_alter_screenshotcomparison_diff_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZulipMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='Zulip message ID or custom tracking ID', max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='pending', max_length=20)),
                ('total_sites', models.IntegerField(default=0)),
                ('successful_sites', models.IntegerField(default=0)),
                ('failed_sites', models.IntegerField(default=0)),
                ('warning_sites', models.IntegerField(default=0)),
                ('results_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('ticket_id', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(default='api', max_length=100)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zulip_messages', to='monitoring.server')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zulip_messages', to='monitoring.site')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['message_id'], name='monitoring__message_ea06da_idx'), models.Index(fields=['server', '-created_at'], name='monitoring__server__76e37a_idx'), models.Index(fields=['site', '-created_at'], name='monitoring__site_id_ca1605_idx'), models.Index(fields=['status'], name='monitoring__status_6d1d8d_idx'), models.Index(fields=['created_at'], name='monitoring__created_e69b0f_idx')],
            },
        ),
    ]
