# Generated by Django 6.0.3 on 2026-04-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_zulipmessage'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='zulipmessage',
            name='monitoring__site_id_ca1605_idx',
        ),
        migrations.RemoveIndex(
            model_name='zulipmessage',
            name='monitoring__created_e69b0f_idx',
        ),
        migrations.AddField(
            model_name='zulipmessage',
            name='sites_pending',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zulipmessage',
            name='sites_processed',
            field=models.IntegerField(default=0),
        ),
    ]
